version: '3.1'
services:
  commonmoder:
    container_name: commonmoder
    build:
      context: .
    network_mode: "host"

    command: python app.py
    restart: always

    env_file:
      - ".env"
