version: '3.1'
services:
  commonmoder:
    container_name: commonmoder
    build:
      context: .

    command: python app.py
    restart: always
    volumes:
    - .:/src
    env_file:
      - ".env"
